# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: addNew.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'addNew.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61\x64\x64New.proto\"\x83\x01\n\x07NewInfo\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\r\x12\r\n\x05title\x18\x02 \x01(\t\x12\x15\n\rauthor_photor\x18\x03 \x01(\t\x12\x11\n\treferring\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x0e\n\x06\x65\x64itor\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\")\n\x0eResultResponse\x12\x17\n\x06result\x18\x01 \x01(\x0e\x32\x07.Result*/\n\x06Result\x12\x11\n\rRESULT_FAILED\x10\x00\x12\x12\n\x0eRESULT_SUCCESS\x10\x01\x32\x33\n\x0bNewsOperate\x12$\n\x07\x61\x64\x64News\x12\x08.NewInfo\x1a\x0f.ResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'addNew_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULT']._serialized_start=193
  _globals['_RESULT']._serialized_end=240
  _globals['_NEWINFO']._serialized_start=17
  _globals['_NEWINFO']._serialized_end=148
  _globals['_RESULTRESPONSE']._serialized_start=150
  _globals['_RESULTRESPONSE']._serialized_end=191
  _globals['_NEWSOPERATE']._serialized_start=242
  _globals['_NEWSOPERATE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
