# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: query.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bquery.proto\"C\n\x0cQueryRequest\x12\x1d\n\tqueryMode\x18\x01 \x01(\x0e\x32\n.QueryMode\x12\x14\n\x0cqueryContent\x18\x02 \x01(\t\"\x1e\n\rQueryResponse\x12\r\n\x05\x64ocId\x18\x01 \x03(\r*%\n\tQueryMode\x12\n\n\x06Normal\x10\x00\x12\x0c\n\x08\x41\x64vanced\x10\x01\x32=\n\x0eQueryProcessor\x12+\n\nQueryDocId\x12\r.QueryRequest\x1a\x0e.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYMODE']._serialized_start=116
  _globals['_QUERYMODE']._serialized_end=153
  _globals['_QUERYREQUEST']._serialized_start=15
  _globals['_QUERYREQUEST']._serialized_end=82
  _globals['_QUERYRESPONSE']._serialized_start=84
  _globals['_QUERYRESPONSE']._serialized_end=114
  _globals['_QUERYPROCESSOR']._serialized_start=155
  _globals['_QUERYPROCESSOR']._serialized_end=216
# @@protoc_insertion_point(module_scope)
