// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: addNew.proto

#include "addNew.pb.h"
#include "addNew.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* NewsOperate_method_names[] = {
  "/NewsOperate/addNews",
};

std::unique_ptr< NewsOperate::Stub> NewsOperate::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NewsOperate::Stub> stub(new NewsOperate::Stub(channel, options));
  return stub;
}

NewsOperate::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_addNews_(NewsOperate_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NewsOperate::Stub::addNews(::grpc::ClientContext* context, const ::NewInfo& request, ::ResultResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NewInfo, ::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_addNews_, context, request, response);
}

void NewsOperate::Stub::async::addNews(::grpc::ClientContext* context, const ::NewInfo* request, ::ResultResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NewInfo, ::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addNews_, context, request, response, std::move(f));
}

void NewsOperate::Stub::async::addNews(::grpc::ClientContext* context, const ::NewInfo* request, ::ResultResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_addNews_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ResultResponse>* NewsOperate::Stub::PrepareAsyncaddNewsRaw(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ResultResponse, ::NewInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_addNews_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ResultResponse>* NewsOperate::Stub::AsyncaddNewsRaw(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncaddNewsRaw(context, request, cq);
  result->StartCall();
  return result;
}

NewsOperate::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NewsOperate_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NewsOperate::Service, ::NewInfo, ::ResultResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NewsOperate::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NewInfo* req,
             ::ResultResponse* resp) {
               return service->addNews(ctx, req, resp);
             }, this)));
}

NewsOperate::Service::~Service() {
}

::grpc::Status NewsOperate::Service::addNews(::grpc::ServerContext* context, const ::NewInfo* request, ::ResultResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


