// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: addNew.proto
#ifndef GRPC_addNew_2eproto__INCLUDED
#define GRPC_addNew_2eproto__INCLUDED

#include "addNew.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class NewsOperate final {
 public:
  static constexpr char const* service_full_name() {
    return "NewsOperate";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status addNews(::grpc::ClientContext* context, const ::NewInfo& request, ::ResultResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResultResponse>> AsyncaddNews(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResultResponse>>(AsyncaddNewsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResultResponse>> PrepareAsyncaddNews(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ResultResponse>>(PrepareAsyncaddNewsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void addNews(::grpc::ClientContext* context, const ::NewInfo* request, ::ResultResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void addNews(::grpc::ClientContext* context, const ::NewInfo* request, ::ResultResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ResultResponse>* AsyncaddNewsRaw(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ResultResponse>* PrepareAsyncaddNewsRaw(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status addNews(::grpc::ClientContext* context, const ::NewInfo& request, ::ResultResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResultResponse>> AsyncaddNews(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResultResponse>>(AsyncaddNewsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResultResponse>> PrepareAsyncaddNews(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ResultResponse>>(PrepareAsyncaddNewsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void addNews(::grpc::ClientContext* context, const ::NewInfo* request, ::ResultResponse* response, std::function<void(::grpc::Status)>) override;
      void addNews(::grpc::ClientContext* context, const ::NewInfo* request, ::ResultResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ResultResponse>* AsyncaddNewsRaw(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ResultResponse>* PrepareAsyncaddNewsRaw(::grpc::ClientContext* context, const ::NewInfo& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_addNews_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status addNews(::grpc::ServerContext* context, const ::NewInfo* request, ::ResultResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_addNews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_addNews() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_addNews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addNews(::grpc::ServerContext* /*context*/, const ::NewInfo* /*request*/, ::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddNews(::grpc::ServerContext* context, ::NewInfo* request, ::grpc::ServerAsyncResponseWriter< ::ResultResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_addNews<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_addNews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_addNews() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::NewInfo, ::ResultResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::NewInfo* request, ::ResultResponse* response) { return this->addNews(context, request, response); }));}
    void SetMessageAllocatorFor_addNews(
        ::grpc::MessageAllocator< ::NewInfo, ::ResultResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::NewInfo, ::ResultResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_addNews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addNews(::grpc::ServerContext* /*context*/, const ::NewInfo* /*request*/, ::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* addNews(
      ::grpc::CallbackServerContext* /*context*/, const ::NewInfo* /*request*/, ::ResultResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_addNews<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_addNews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_addNews() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_addNews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addNews(::grpc::ServerContext* /*context*/, const ::NewInfo* /*request*/, ::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_addNews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_addNews() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_addNews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addNews(::grpc::ServerContext* /*context*/, const ::NewInfo* /*request*/, ::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestaddNews(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_addNews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_addNews() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->addNews(context, request, response); }));
    }
    ~WithRawCallbackMethod_addNews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status addNews(::grpc::ServerContext* /*context*/, const ::NewInfo* /*request*/, ::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* addNews(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_addNews : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_addNews() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::NewInfo, ::ResultResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::NewInfo, ::ResultResponse>* streamer) {
                       return this->StreamedaddNews(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_addNews() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status addNews(::grpc::ServerContext* /*context*/, const ::NewInfo* /*request*/, ::ResultResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedaddNews(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::NewInfo,::ResultResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_addNews<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_addNews<Service > StreamedService;
};


#endif  // GRPC_addNew_2eproto__INCLUDED
