// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: addNew.proto
// Protobuf C++ Version: 5.29.2

#include "addNew.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr ResultResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{static_cast< ::Result >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ResultResponse::ResultResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ResultResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResultResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResultResponseDefaultTypeInternal() {}
  union {
    ResultResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResultResponseDefaultTypeInternal _ResultResponse_default_instance_;

inline constexpr NewInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : title_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        author_photor_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        referring_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        source_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        editor_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        doc_id_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR NewInfo::NewInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct NewInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR NewInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~NewInfoDefaultTypeInternal() {}
  union {
    NewInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 NewInfoDefaultTypeInternal _NewInfo_default_instance_;
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_addNew_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_addNew_2eproto = nullptr;
const ::uint32_t
    TableStruct_addNew_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::NewInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::NewInfo, _impl_.doc_id_),
        PROTOBUF_FIELD_OFFSET(::NewInfo, _impl_.title_),
        PROTOBUF_FIELD_OFFSET(::NewInfo, _impl_.author_photor_),
        PROTOBUF_FIELD_OFFSET(::NewInfo, _impl_.referring_),
        PROTOBUF_FIELD_OFFSET(::NewInfo, _impl_.source_),
        PROTOBUF_FIELD_OFFSET(::NewInfo, _impl_.editor_),
        PROTOBUF_FIELD_OFFSET(::NewInfo, _impl_.content_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ResultResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::ResultResponse, _impl_.result_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::NewInfo)},
        {15, -1, -1, sizeof(::ResultResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_NewInfo_default_instance_._instance,
    &::_ResultResponse_default_instance_._instance,
};
const char descriptor_table_protodef_addNew_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014addNew.proto\"\203\001\n\007NewInfo\022\016\n\006doc_id\030\001 \001"
    "(\r\022\r\n\005title\030\002 \001(\t\022\025\n\rauthor_photor\030\003 \001(\t"
    "\022\021\n\treferring\030\004 \001(\t\022\016\n\006source\030\005 \001(\t\022\016\n\006e"
    "ditor\030\006 \001(\t\022\017\n\007content\030\007 \001(\t\")\n\016ResultRe"
    "sponse\022\027\n\006result\030\001 \001(\0162\007.Result*/\n\006Resul"
    "t\022\021\n\rRESULT_FAILED\020\000\022\022\n\016RESULT_SUCCESS\020\001"
    "23\n\013NewsOperate\022$\n\007addNews\022\010.NewInfo\032\017.R"
    "esultResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_addNew_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_addNew_2eproto = {
    false,
    false,
    301,
    descriptor_table_protodef_addNew_2eproto,
    "addNew.proto",
    &descriptor_table_addNew_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_addNew_2eproto::offsets,
    file_level_enum_descriptors_addNew_2eproto,
    file_level_service_descriptors_addNew_2eproto,
};
const ::google::protobuf::EnumDescriptor* Result_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_addNew_2eproto);
  return file_level_enum_descriptors_addNew_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t Result_internal_data_[] = {
    131072u, 0u, };
bool Result_IsValid(int value) {
  return 0 <= value && value <= 1;
}
// ===================================================================

class NewInfo::_Internal {
 public:
};

NewInfo::NewInfo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:NewInfo)
}
inline PROTOBUF_NDEBUG_INLINE NewInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::NewInfo& from_msg)
      : title_(arena, from.title_),
        author_photor_(arena, from.author_photor_),
        referring_(arena, from.referring_),
        source_(arena, from.source_),
        editor_(arena, from.editor_),
        content_(arena, from.content_),
        _cached_size_{0} {}

NewInfo::NewInfo(
    ::google::protobuf::Arena* arena,
    const NewInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  NewInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.doc_id_ = from._impl_.doc_id_;

  // @@protoc_insertion_point(copy_constructor:NewInfo)
}
inline PROTOBUF_NDEBUG_INLINE NewInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : title_(arena),
        author_photor_(arena),
        referring_(arena),
        source_(arena),
        editor_(arena),
        content_(arena),
        _cached_size_{0} {}

inline void NewInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.doc_id_ = {};
}
NewInfo::~NewInfo() {
  // @@protoc_insertion_point(destructor:NewInfo)
  SharedDtor(*this);
}
inline void NewInfo::SharedDtor(MessageLite& self) {
  NewInfo& this_ = static_cast<NewInfo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.title_.Destroy();
  this_._impl_.author_photor_.Destroy();
  this_._impl_.referring_.Destroy();
  this_._impl_.source_.Destroy();
  this_._impl_.editor_.Destroy();
  this_._impl_.content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* NewInfo::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) NewInfo(arena);
}
constexpr auto NewInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(NewInfo),
                                            alignof(NewInfo));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull NewInfo::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_NewInfo_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &NewInfo::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<NewInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &NewInfo::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<NewInfo>(), &NewInfo::ByteSizeLong,
            &NewInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(NewInfo, _impl_._cached_size_),
        false,
    },
    &NewInfo::kDescriptorMethods,
    &descriptor_table_addNew_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* NewInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 62, 2> NewInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::NewInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint32 doc_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(NewInfo, _impl_.doc_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.doc_id_)}},
    // string title = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.title_)}},
    // string author_photor = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.author_photor_)}},
    // string referring = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.referring_)}},
    // string source = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.source_)}},
    // string editor = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.editor_)}},
    // string content = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.content_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint32 doc_id = 1;
    {PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.doc_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // string title = 2;
    {PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.title_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string author_photor = 3;
    {PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.author_photor_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string referring = 4;
    {PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.referring_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string source = 5;
    {PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.source_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string editor = 6;
    {PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.editor_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string content = 7;
    {PROTOBUF_FIELD_OFFSET(NewInfo, _impl_.content_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\7\0\5\15\11\6\6\7"
    "NewInfo"
    "title"
    "author_photor"
    "referring"
    "source"
    "editor"
    "content"
  }},
};

PROTOBUF_NOINLINE void NewInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:NewInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.title_.ClearToEmpty();
  _impl_.author_photor_.ClearToEmpty();
  _impl_.referring_.ClearToEmpty();
  _impl_.source_.ClearToEmpty();
  _impl_.editor_.ClearToEmpty();
  _impl_.content_.ClearToEmpty();
  _impl_.doc_id_ = 0u;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* NewInfo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const NewInfo& this_ = static_cast<const NewInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* NewInfo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const NewInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:NewInfo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint32 doc_id = 1;
          if (this_._internal_doc_id() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                1, this_._internal_doc_id(), target);
          }

          // string title = 2;
          if (!this_._internal_title().empty()) {
            const std::string& _s = this_._internal_title();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NewInfo.title");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string author_photor = 3;
          if (!this_._internal_author_photor().empty()) {
            const std::string& _s = this_._internal_author_photor();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NewInfo.author_photor");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // string referring = 4;
          if (!this_._internal_referring().empty()) {
            const std::string& _s = this_._internal_referring();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NewInfo.referring");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          // string source = 5;
          if (!this_._internal_source().empty()) {
            const std::string& _s = this_._internal_source();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NewInfo.source");
            target = stream->WriteStringMaybeAliased(5, _s, target);
          }

          // string editor = 6;
          if (!this_._internal_editor().empty()) {
            const std::string& _s = this_._internal_editor();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NewInfo.editor");
            target = stream->WriteStringMaybeAliased(6, _s, target);
          }

          // string content = 7;
          if (!this_._internal_content().empty()) {
            const std::string& _s = this_._internal_content();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "NewInfo.content");
            target = stream->WriteStringMaybeAliased(7, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:NewInfo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t NewInfo::ByteSizeLong(const MessageLite& base) {
          const NewInfo& this_ = static_cast<const NewInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t NewInfo::ByteSizeLong() const {
          const NewInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:NewInfo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string title = 2;
            if (!this_._internal_title().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_title());
            }
            // string author_photor = 3;
            if (!this_._internal_author_photor().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_author_photor());
            }
            // string referring = 4;
            if (!this_._internal_referring().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_referring());
            }
            // string source = 5;
            if (!this_._internal_source().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_source());
            }
            // string editor = 6;
            if (!this_._internal_editor().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_editor());
            }
            // string content = 7;
            if (!this_._internal_content().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_content());
            }
            // uint32 doc_id = 1;
            if (this_._internal_doc_id() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_doc_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void NewInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<NewInfo*>(&to_msg);
  auto& from = static_cast<const NewInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:NewInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_title().empty()) {
    _this->_internal_set_title(from._internal_title());
  }
  if (!from._internal_author_photor().empty()) {
    _this->_internal_set_author_photor(from._internal_author_photor());
  }
  if (!from._internal_referring().empty()) {
    _this->_internal_set_referring(from._internal_referring());
  }
  if (!from._internal_source().empty()) {
    _this->_internal_set_source(from._internal_source());
  }
  if (!from._internal_editor().empty()) {
    _this->_internal_set_editor(from._internal_editor());
  }
  if (!from._internal_content().empty()) {
    _this->_internal_set_content(from._internal_content());
  }
  if (from._internal_doc_id() != 0) {
    _this->_impl_.doc_id_ = from._impl_.doc_id_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void NewInfo::CopyFrom(const NewInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NewInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void NewInfo::InternalSwap(NewInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.title_, &other->_impl_.title_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.author_photor_, &other->_impl_.author_photor_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.referring_, &other->_impl_.referring_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.source_, &other->_impl_.source_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.editor_, &other->_impl_.editor_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.content_, &other->_impl_.content_, arena);
        swap(_impl_.doc_id_, other->_impl_.doc_id_);
}

::google::protobuf::Metadata NewInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ResultResponse::_Internal {
 public:
};

ResultResponse::ResultResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ResultResponse)
}
ResultResponse::ResultResponse(
    ::google::protobuf::Arena* arena, const ResultResponse& from)
    : ResultResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ResultResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ResultResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
ResultResponse::~ResultResponse() {
  // @@protoc_insertion_point(destructor:ResultResponse)
  SharedDtor(*this);
}
inline void ResultResponse::SharedDtor(MessageLite& self) {
  ResultResponse& this_ = static_cast<ResultResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ResultResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ResultResponse(arena);
}
constexpr auto ResultResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(ResultResponse),
                                            alignof(ResultResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ResultResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ResultResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ResultResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ResultResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ResultResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ResultResponse>(), &ResultResponse::ByteSizeLong,
            &ResultResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_._cached_size_),
        false,
    },
    &ResultResponse::kDescriptorMethods,
    &descriptor_table_addNew_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ResultResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ResultResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ResultResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .Result result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ResultResponse, _impl_.result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .Result result = 1;
    {PROTOBUF_FIELD_OFFSET(ResultResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ResultResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:ResultResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ResultResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ResultResponse& this_ = static_cast<const ResultResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ResultResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ResultResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:ResultResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .Result result = 1;
          if (this_._internal_result() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_result(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:ResultResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ResultResponse::ByteSizeLong(const MessageLite& base) {
          const ResultResponse& this_ = static_cast<const ResultResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ResultResponse::ByteSizeLong() const {
          const ResultResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:ResultResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // .Result result = 1;
            if (this_._internal_result() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_result());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ResultResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ResultResponse*>(&to_msg);
  auto& from = static_cast<const ResultResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ResultResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ResultResponse::CopyFrom(const ResultResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ResultResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ResultResponse::InternalSwap(ResultResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata ResultResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_addNew_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
