// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: query.proto

#include "query.pb.h"
#include "query.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* QueryProcessor_method_names[] = {
  "/QueryProcessor/QueryDocId",
};

std::unique_ptr< QueryProcessor::Stub> QueryProcessor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< QueryProcessor::Stub> stub(new QueryProcessor::Stub(channel, options));
  return stub;
}

QueryProcessor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_QueryDocId_(QueryProcessor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status QueryProcessor::Stub::QueryDocId(::grpc::ClientContext* context, const ::QueryRequest& request, ::QueryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::QueryRequest, ::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryDocId_, context, request, response);
}

void QueryProcessor::Stub::async::QueryDocId(::grpc::ClientContext* context, const ::QueryRequest* request, ::QueryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::QueryRequest, ::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryDocId_, context, request, response, std::move(f));
}

void QueryProcessor::Stub::async::QueryDocId(::grpc::ClientContext* context, const ::QueryRequest* request, ::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryDocId_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::QueryResponse>* QueryProcessor::Stub::PrepareAsyncQueryDocIdRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::QueryResponse, ::QueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryDocId_, context, request);
}

::grpc::ClientAsyncResponseReader< ::QueryResponse>* QueryProcessor::Stub::AsyncQueryDocIdRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryDocIdRaw(context, request, cq);
  result->StartCall();
  return result;
}

QueryProcessor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QueryProcessor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QueryProcessor::Service, ::QueryRequest, ::QueryResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](QueryProcessor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::QueryRequest* req,
             ::QueryResponse* resp) {
               return service->QueryDocId(ctx, req, resp);
             }, this)));
}

QueryProcessor::Service::~Service() {
}

::grpc::Status QueryProcessor::Service::QueryDocId(::grpc::ServerContext* context, const ::QueryRequest* request, ::QueryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


