// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: query.proto
#ifndef GRPC_query_2eproto__INCLUDED
#define GRPC_query_2eproto__INCLUDED

#include "query.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

class QueryProcessor final {
 public:
  static constexpr char const* service_full_name() {
    return "QueryProcessor";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status QueryDocId(::grpc::ClientContext* context, const ::QueryRequest& request, ::QueryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::QueryResponse>> AsyncQueryDocId(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::QueryResponse>>(AsyncQueryDocIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::QueryResponse>> PrepareAsyncQueryDocId(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::QueryResponse>>(PrepareAsyncQueryDocIdRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void QueryDocId(::grpc::ClientContext* context, const ::QueryRequest* request, ::QueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void QueryDocId(::grpc::ClientContext* context, const ::QueryRequest* request, ::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::QueryResponse>* AsyncQueryDocIdRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::QueryResponse>* PrepareAsyncQueryDocIdRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status QueryDocId(::grpc::ClientContext* context, const ::QueryRequest& request, ::QueryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::QueryResponse>> AsyncQueryDocId(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::QueryResponse>>(AsyncQueryDocIdRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::QueryResponse>> PrepareAsyncQueryDocId(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::QueryResponse>>(PrepareAsyncQueryDocIdRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void QueryDocId(::grpc::ClientContext* context, const ::QueryRequest* request, ::QueryResponse* response, std::function<void(::grpc::Status)>) override;
      void QueryDocId(::grpc::ClientContext* context, const ::QueryRequest* request, ::QueryResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::QueryResponse>* AsyncQueryDocIdRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::QueryResponse>* PrepareAsyncQueryDocIdRaw(::grpc::ClientContext* context, const ::QueryRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_QueryDocId_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status QueryDocId(::grpc::ServerContext* context, const ::QueryRequest* request, ::QueryResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_QueryDocId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_QueryDocId() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_QueryDocId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDocId(::grpc::ServerContext* /*context*/, const ::QueryRequest* /*request*/, ::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryDocId(::grpc::ServerContext* context, ::QueryRequest* request, ::grpc::ServerAsyncResponseWriter< ::QueryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_QueryDocId<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_QueryDocId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_QueryDocId() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::QueryRequest, ::QueryResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::QueryRequest* request, ::QueryResponse* response) { return this->QueryDocId(context, request, response); }));}
    void SetMessageAllocatorFor_QueryDocId(
        ::grpc::MessageAllocator< ::QueryRequest, ::QueryResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::QueryRequest, ::QueryResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_QueryDocId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDocId(::grpc::ServerContext* /*context*/, const ::QueryRequest* /*request*/, ::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryDocId(
      ::grpc::CallbackServerContext* /*context*/, const ::QueryRequest* /*request*/, ::QueryResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_QueryDocId<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_QueryDocId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_QueryDocId() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_QueryDocId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDocId(::grpc::ServerContext* /*context*/, const ::QueryRequest* /*request*/, ::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_QueryDocId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_QueryDocId() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_QueryDocId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDocId(::grpc::ServerContext* /*context*/, const ::QueryRequest* /*request*/, ::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQueryDocId(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_QueryDocId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_QueryDocId() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->QueryDocId(context, request, response); }));
    }
    ~WithRawCallbackMethod_QueryDocId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status QueryDocId(::grpc::ServerContext* /*context*/, const ::QueryRequest* /*request*/, ::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* QueryDocId(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_QueryDocId : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_QueryDocId() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::QueryRequest, ::QueryResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::QueryRequest, ::QueryResponse>* streamer) {
                       return this->StreamedQueryDocId(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_QueryDocId() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status QueryDocId(::grpc::ServerContext* /*context*/, const ::QueryRequest* /*request*/, ::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQueryDocId(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::QueryRequest,::QueryResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_QueryDocId<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_QueryDocId<Service > StreamedService;
};


#endif  // GRPC_query_2eproto__INCLUDED
