# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: search.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csearch.proto\";\n\rSearchRequest\x12\x19\n\x04mode\x18\x01 \x01(\x0e\x32\x0b.SearchMode\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\" \n\x0eSearchResponse\x12\x0e\n\x06\x64ocIds\x18\x01 \x03(\x05\" \n\x0eGetNewsRequest\x12\x0e\n\x06\x64ocIds\x18\x01 \x03(\x05\"\x1f\n\x0fGetNewsResponse\x12\x0c\n\x04news\x18\x01 \x03(\t*&\n\nSearchMode\x12\n\n\x06Normal\x10\x00\x12\x0c\n\x08\x41\x64vanced\x10\x01\x32l\n\rSearchService\x12)\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\x12\x30\n\x07GetNews\x12\x0f.GetNewsRequest\x1a\x10.GetNewsResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHMODE']._serialized_start=178
  _globals['_SEARCHMODE']._serialized_end=216
  _globals['_SEARCHREQUEST']._serialized_start=16
  _globals['_SEARCHREQUEST']._serialized_end=75
  _globals['_SEARCHRESPONSE']._serialized_start=77
  _globals['_SEARCHRESPONSE']._serialized_end=109
  _globals['_GETNEWSREQUEST']._serialized_start=111
  _globals['_GETNEWSREQUEST']._serialized_end=143
  _globals['_GETNEWSRESPONSE']._serialized_start=145
  _globals['_GETNEWSRESPONSE']._serialized_end=176
  _globals['_SEARCHSERVICE']._serialized_start=218
  _globals['_SEARCHSERVICE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
